[package]
name = "personal-ai-storage-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
personal-ai-domain.workspace = true
personal-ai-storage.workspace = true
personal-ai-agent-core.workspace = true
serde_json.workspace = true
sqlx.workspace = true
uuid.workspace = true

[dev-dependencies]
personal-ai-storage-s3 = { path = "../storage-s3" }
tokio.workspace = true

[lints]
workspace = true
